project:
  type: website
  output-dir: docs

website:
  title: "Angel Alcala Ruiz"
  search:
    location: navbar
    type: textbox
  navbar:
    background: "#83C6D2"
    right:
      - text: "Home"
        file: index.qmd
      - text: "Mathematics"
        file: math-notes.qmd
      - text: "Programming"
        file: programming-projects.qmd
      - text: "Portfolio"
        file: portfolio.qmd
      - text: "Artwork"
        file: artwork.qmd

  sidebar:  
    - title: "Mathematics"
      style: "docked"
      contents:
        - mathematics.qmd
    - title: "Programming"
      style: "docked"
      contents:
        - programming-projects.qmd
        - project-euler-exercises.qmd

  page-footer: 
    background: "#83C6D2"
    left: "Copyright 2023, Angel Alcala Ruiz" 
    center: 
      - icon: linkedin
        href: https://www.linkedin.com/in/dejesusalcala/ 
      - icon: github
        href: https://github.com/dejesusalcala
      - icon: envelope-at-fill
        href: mailto:dejesusalcala@gmail.com
    right: |  
      [Made with Quarto](https://quarto.org/){target="_blank"}
format:
  html:
    theme: spacelab
    css: styles.css
    toc: true



