---
title: "Welcome"
---

Hello! My name is Angel and I'd like to welcome you to my website. I want to use this space as a way to continue my journey of learning, and to be able to share some of my knowledge.

I graduated from the [University of California, Berkeley](https://www.berkeley.edu/){target="_blank"} with a bachelor's in [applied mathematics](https://math.berkeley.edu/undergraduate/major/applied){target="_blank"}. I enjoy using mathematics to help find solutions to real-world problems. I'm specifically interested in data analysis to create visualizations that can help us better understand an issue which can lead us to have thoughtful discussions about possible solutions.

I have two amazing little sisters (technically my nieces!) that I absolutely love spending so much time with. On my free time I enjoy weight lifting, mountain biking, calligraphy, and painting.

If you have any questions about my work or if you would like to contact me about anything else, then please feel free to contact me through [LinkedIn](https://www.linkedin.com/in/dejesusalcala/){target="_blank"} or by [email](mailto:dejesusalcala@gmail.com).

Best,

Angel