---
title: "Portfolio"
format: html
---

1. [Hurricane Analysis](https://dejesusalcala.github.io/hurricane_analysis/#analysis){target="_blank"}

    - **Summary:** An analysis on tropical cyclones in the North Atlantic region. The project includes both the data preparation stage and the analysis stage of the ***data analysis cycle***. In the preparation stage the data is cleaned by selecting the columns that will be used, specifying missing values, specifying data-types, and removing outliers. The analysis performed is in the form of ***statistics*** and ***data visualizations*** using ***R***’s ***ggplot2*** and ***dplyr*** packages.

    - **Skills:** *R, ggplot2, dplyr, Data Analysis, Data Visualization*

2. [Inaugural Speech Analysis](https://dejesusalcala.shinyapps.io/InauguralSpeechAnalysis/){target="_blank"}

    - **Summary:** Built an interactive application through ***R***’s ***Shiny*** package to perform a ***text analysis***. The application allows the user to explore the most frequently used words and bigrams of the U.S. president’s inaugural speeches with the ability to remove stopwords.

    - **Skills:** *R, Shiny, ggplot2, dplyr, Data Visualization*

3. [Investment Simulator](https://dejesusalcala.shinyapps.io/InvestmentSimulator/){target="_blank"} 

    - **Summary:** Built an interactive investment application through ***R***’s ***Shiny*** package. The application uses simulations to visualize how an investment account will grow given an initial amount and yearly contributions.

    - **Skills:** *R, Shiny, ggplot2, dplyr, Data Visualization*

4. [Savings Rate Calculator](https://dejesusalcala.shinyapps.io/SavingsRateCalculator/){target="_blank"} 

    - **Summary:** A savings calculator application to compute the number of years of saving a percentage of one's income it would take to reach a target amount given an annual income and an annual rate.

    - **Skills:** *R, Shiny, ggplot2, dplyr, Data Visualization*

5. [SQL Discussion](https://dejesusalcala.github.io/sql-discussion/){target="_blank"}

    - **Summary:** In this SQL discussion we go through examples of creating tables, joining multiple tables, and aggregation over multiple rows. 