---
title: "Nonlinear & Discrete Optimization"
format: html
---

## Course

#### Title

**IND ENG 160**: Nonlinear and Discrete Optimization 

#### Official Course Desctiption

This course introduces unconstrained and constrained optimization with continuous and discrete domains. Convex sets and convex functions; local optimality; KKT conditions; Lagrangian duality; steepest descent and Newton's method. Modeling with integer variables; branch-and-bound method; cutting planes. Models on production/inventory planning, logistics, portfolio optimization, factor modeling, classification with support vector machines.

For more information about **IND ENG 160** visit [Berkeley's Academic Guide](https://guide.berkeley.edu/courses/ind_eng/){target="_blank"}.

## Class Notes

- [IND ENG 160 Notes](https://drive.google.com/file/d/1zaunvyhQlbXzFnlyi0w-aB4yH-A7xv8d/view){target="_blank"}


## Homework

- [Homework 1](https://drive.google.com/file/d/1ESoQViPQaLAUVcbap78YX3Ld6WOdVwja/view?usp=drive_link){target="_blank"} - [My Solutions](https://drive.google.com/file/d/1cXgfbR-4sykCd25QXC2xAzmIYJtbS5Rf/view?usp=drive_link){target="_blank"}

- [Homework 2](https://drive.google.com/file/d/1qH8Scz3jxhnG5dxKosAcWWuhXBg4t7Zf/view?usp=drive_link){target="_blank"} - [My Solutions](https://drive.google.com/file/d/1sDRTx1KXs_R6EVnqLrnMrflkXtZf-7Mn/view?usp=drive_link){target="_blank"}

- [Homework 3](https://drive.google.com/file/d/1ooEDtH1Po_ehUXE6-D1x10UgV1EPtns1/view?usp=drive_link){target="_blank"} - [My Solutions](https://drive.google.com/file/d/1HT51z5yO8Sy6WaHOiELWDKviRx3YxS_A/view?usp=drive_link){target="_blank"}

- [Homework 4](https://drive.google.com/file/d/1rUaSz3RVCwQIExfw4lwljZTI_3OeVc6R/view?usp=drive_link){target="_blank"} - [My Solutions](https://drive.google.com/file/d/1-lPx0plJOLx6bDfsCDCEgfjjZL09vmm5/view?usp=drive_link){target="_blank"}